travel/config/routes.rb
Rails.application.routes.draw do

  resources :friends

  resources :comments, only: [:create, :index]

  resources :suggestions, only: [:create, :destroy, :index]

  resources :trips

  resources :users

  resource :session, only: [:new, :create, :destroy]

  get '/logout' => 'sessions#destroy'

  get '/suggestion/:id/upvote' => 'suggestions#upvote'

  get '/suggestion/:id/downvote' => 'suggestions#downvote'

  get '/suggestion/:id/getcomments' => 'comments#suggestion_comments'

  get '/suggestion/:category_id/all' => 'suggestions#index'

  get '/suggestion/:id/show' => 'suggestions#show'

  get '/categories/:trip_id' => 'categories#index'

  get '/categories/:id/show' => 'categories#show'

  get '/return_current_user' => 'mains#return_current_user'

  get '/usertrip' => 'trips#user_trip'

  get '/userfriends' => 'friends#user_friends'

  get '/' => 'mains#index'

end

travel/app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :trip
  has_many :suggestions
end

travel/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    id = params[:trip_id]
    @categories = Category.where(trip_id: id).all
    respond_to do |format|
      format.json { render json: @categories }
      format.html 
    end
  end

  def show
    id = params[:id]
    @category = Category.find(id)
    respond_to do |format|
      format.json { render json: @category }
    end
  end

end

travel/app/helpers/categories_helper.rb
module CategoriesHelper
end

travel/app/views/categories/_form.html.erb
<%= form_for(@categories) do |f| %>
  <% if @categories.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@categories.errors.count, "error") %> something prohibited this category from being saved:</h2>

      <ul>
      <% @categories.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :name 'Name of Category' %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

travel/app/views/categories/index.html.erb
<h1>Categories</h1>

    <% @categories.each do |category| %>
        <h2><%= category.name %></h2>
        <p><%= link_to 'Suggestions', suggestions_path %></p>
    <% end %>

travel/app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', trips_path %>