travel/config/routes.rb
Rails.application.routes.draw do

  resources :friends

  resources :comments, only: [:create, :index]

  resources :suggestions, only: [:create, :destroy, :index]

  resources :trips

  resources :users

  resource :session, only: [:new, :create, :destroy]

  get '/logout' => 'sessions#destroy'

  get '/suggestion/:id/upvote' => 'suggestions#upvote'

  get '/suggestion/:id/downvote' => 'suggestions#downvote'

  get '/suggestion/:id/getcomments' => 'comments#suggestion_comments'

  get '/suggestion/:category_id/all' => 'suggestions#index'

  get '/suggestion/:id/show' => 'suggestions#show'

  get '/categories/:trip_id' => 'categories#index'

  get '/categories/:id/show' => 'categories#show'

  get '/return_current_user' => 'mains#return_current_user'

  get '/usertrip' => 'trips#user_trip'

  get '/userfriends' => 'friends#user_friends'

  get '/' => 'mains#index'

end

travel/app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :user
  has_one :group
  has_many :categories
end

travel/app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]
  before_action :require_current_user


  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
  end

  def user_trip
    @trip = Trip.where(user_id: current_user.id)
    respond_to do |format|
      format.json { render json: @trip }
    end
  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(trip_params)
    @group = Group.create(user_id: current_user.id)
    @trip.update(group_id: @group.id, user_id: current_user.id)

    respond_to do |format|
      if @trip.save
        @group.update(trip_id: @trip.id)
        @food = Category.create(name: 'food', trip_id: @trip.id)
        @lodging = Category.create(name: 'lodging', trip_id: @trip.id)
        @adventure = Category.create(name: 'adventure', trip_id: @trip.id)
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:location, :title, :description, :duration)
    end
end

travel/app/helpers/trips_helper.rb
module TripsHelper
end

travel/app/views/trips/_form.html.erb
<%= form_for(@trip) do |f| %>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.text_field :duration %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

travel/app/views/trips/edit.html.erb
<h1>Editing Trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

travel/app/views/trips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Trips</h1>

<table>
  <thead>
    <tr>
      <th>Group</th>
      <th>Location</th>
      <th>Title</th>
      <th>Description</th>
      <th>Duration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td><%= trip.group_id %></td>
        <td><%= trip.location %></td>
        <td><%= trip.title %></td>
        <td><%= trip.description %></td>
        <td><%= trip.duration %></td>
        <td><%= link_to 'Show', trip %></td>
        <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
        <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trip', new_trip_path %>

travel/app/views/trips/new.html.erb
<h1>New Trip</h1>

<%= render 'form' %>

<%= link_to 'Back', trips_path %>

travel/app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Group:</strong>
  <%= @trip.group_id %>
</p>

<p>
  <strong>Location:</strong>
  <%= @trip.location %>
</p>

<p>
  <strong>Title:</strong>
  <%= @trip.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @trip.description %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @trip.duration %>
</p>


<%= link_to 'Edit', edit_trip_path(@trip) %>
<%= link_to 'Back to All trips', trips_path %>
<%= link_to 'Categories', "/categories/#{@trip.id}" %>